### ISSUE TITLE
new UCI editor make.powerapps

### ISSUE THREAD

**Issue by Herald1360** [adityadash03/PCFTwoOptionButton#1]
Hi, if I use this PCF in a model driven form in D365 CE then the form can't be loaded anymore in make.powerapps new editor. Any idea ?

**Comment by adityadash03** [comment]
> Hi, if I use this PCF in a model driven form in D365 CE then the form can't be loaded anymore in make.powerapps new editor. Any idea ?

Hi, It is working with maker.powerapps.com. Can you please check
