### ISSUE TITLE
"No" Options do not show after refresh

### ISSUE THREAD

**Issue by DigitalFlow** [adityadash03/PCFTwoOptionButton#3]
Hi @adityadash03,

thanks for providing this PCF.

We are experiencing a bug with it:
When you set the value to false, the false option is correctly highlighted in your control.
Saving this value works as well.

However when you refresh the page, the "No" option is not highlighted anymore.
This works for "Yes" options.

In addition to that, you should increase the version number in your ControlManifest.Input.xml, when you leave it at the same verison all the time (version="0.0.1"), the PCF does not get updated in the organizations when you import the solution.

It would be great if you could fix this.

EDIT: I looked on the code of the last release. In your latest release the code is different, so this might be fixed. Can you push a new release with an incremented version number, so that the PCF correctly updates in the organization?

Kind Regards,
Florian

**Comment by adityadash03** [comment]
Can you please try now. I updated version. This issue is fixed

**Comment by adityadash03** [comment]
> Hi @adityadash03,
> 
> thanks for providing this PCF.
> 
> We are experiencing a bug with it:
> When you set the value to false, the false option is correctly highlighted in your control.
> Saving this value works as well.
> 
> However when you refresh the page, the "No" option is not highlighted anymore.
> This works for "Yes" options.
> 
> In addition to that, you should increase the version number in your ControlManifest.Input.xml, when you leave it at the same verison all the time (version="0.0.1"), the PCF does not get updated in the organizations when you import the solution.
> 
> It would be great if you could fix this.
> 
> EDIT: I looked on the code of the last release. In your latest release the code is different, so this might be fixed. Can you push a new release with an incremented version number, so that the PCF correctly updates in the organization?
> 
> Kind Regards,
> Florian
Can you please try now. I updated version. This issue is fixed

**Comment by DigitalFlow** [comment]
Hi @adityadash03,

fixed for us, thanks a lot :)

Kind Regards,
Florian
